# Generated by Django 6.0.7 on 2026-07-15 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('editors', models.ManyToManyField(blank=True, related_name='publisher_editors', to=settings.AUTH_USER_MODEL)),
                ('journalists', models.ManyToManyField(blank=True, related_name='publisher_journalists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
