# Generated by Django 6.0.7 on 2026-07-21 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_approvedarticlelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='publisher_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='publisher_journalists', to=settings.AUTH_USER_MODEL),
        ),
    ]
